#!/bin/bash

# ================================================================
#
# Zmamp
#
# @author Akihiro Fukaya <akihiro.fukaya@seezoo.co.jp>
#
# ================================================================

function Include_conf()
{
  MAMPDIR="/Applications/MAMP"
  BINDIR="${MAMPDIR}/bin"
  PHPDIR="${BINDIR}/php"
  CONFDIR="${MAMPDIR}/conf"
  HTTPD_CONF="${CONFDIR}/apache/httpd.conf"
}

function HELP()
{
  echo ""
  echo "Usage: Zmamp [start]"
  echo "             [stop]"
  echo "             [php] [-v|-cv|-cfg|-a]"
  echo "             [httpd] [start|stop|restart|status|conf]"
  echo "             [mysqld] [start|stop|restart|status]"
  echo ""
  echo "Options:"
  echo "  start                      Starting the apache and mysql of MAMP"
  echo "  stop                       Stop apache and mysql of MAMP"
  echo "  php"
  echo "    -v   | --version         PHP version confirmation of MAMP"
  echo "    -cv  | --change-version  Change PHP version for Default and MAMP"
  echo "    -cfg | --conf            Change the php.ini of the MAMP php"
  echo "    -a                       Develop tool"
  echo "  httpd"
  echo "    start                    Starting the apache of MAMP"
  echo "    stop                     Stop the apache of MAMP"
  echo "    restart                  Restarting the apache of MAMP"
  echo "    status                   Check the status of the apache of MAMP"
  echo "    conf                     Change the httpd.conf"
  echo "  mysqld"
  echo "    start                    Starting the mysqld of MAMP"
  echo "    stop                     Stop the mysqld of MAMP"
  echo "    restart                  Restarting the mysqld of MAMP"
  echo "    status                   Check the status of the mysqld of MAMP"
}

function Main()
{
  local prog="Zmamp"
  Include_conf

  case ${1} in
    start | stop | status)
      MAMP "${1}"
      ;;
    httpd )
      case ${2} in
        start | stop | restart | status | conf)
          HTTPD && ${2}
          ;;
        *)
          HELP
          ;;
      esac
      ;;
    mysqld )
      case ${2} in
        start | stop | restart | status )
          MYSQLD && ${2}
          ;;
        *)
          HELP
          ;;
      esac
      ;;
    php )
      PHP
      case ${2} in
        -v | --check-ver)
          check
          ;;
        -cv | --conf-ver)
          change
          ;;
        -cfg | --conf)
          conf
          ;;
        -a)
          a ${2}
          ;;
        *)
          HELP
          ;;
      esac
      ;;
    -h | --help | * )
      HELP
      ;;
  esac

  return 0
}

function MAMP()
{
  local r=0
  HTTPD && ${1} || r=1
  MYSQLD && ${1} || r=1
  return ${r}
}

function HTTPD()
{
  SERVICE="httpd"

  # start
  function start()
  {
    echo "Start ${SERVICE}."

    _status && echo "${SERVICE} already running..." && return 0

    if sudo ${BINDIR}/startApache.sh;then
      _wait "HTTPD" "start" && echo " [ OK ]" || echo " [ Failed ]"
    else
      Err "httpd start failed."
    fi

    return 0
  }

  # stop
  function stop()
  {
    echo "Stop ${SERVICE}."

    ! _status && echo "${SERVICE} already stopped." && return 0

    if sudo ${BINDIR}/stopApache.sh;then
      _wait "HTTPD" "stop" && echo "[ OK ]" || echo "[ Failed ]"
    else
      Err "httpd stop failed."
    fi

    return 0
  }

  # restart
  function restart()
  {
    _status && stop
    start

    return 0
  }

  # status
  function status()
  {
    _status && echo "${SERVICE} is running..." || echo "${SERVICE} is stop."
    return 0
  }

  # _status
  function _status()
  {
    # return code
    # 0: Is running
    # 1: Stoped

    ps cax | grep httpd > /dev/null
    return $?
  }

  # conf
  function conf()
  {
    echo "To change the httpd.conf file ?"
    ! _ynselecter && return 0

    [ ! -e ${HTTPD_CONF} ] && Err "'httpd.conf' is not found."

    local _STAT="stat -f "%m" ${HTTPD_CONF}"
    local _ftime=$(${_STAT})

    while vi ${HTTPD_CONF} || :;do
      echo "Edit the end ?"
      if _ynselecter ;then
        [ "$(${_STAT})" != "${_ftime}" ] && restart && return 0 || return 0
      fi
    done
  }

  return 0
}

#  mysqld main
function MYSQLD()
{
  SERVICE="mysqld"

  # start
  function start()
  {
    _status &&  echo "${SERVICE} is already running." && return 0

    echo "Start ${SERVICE}."
    nohup ${BINDIR}/startMysql.sh > /dev/null

    _wait "MYSQLD" "start" && echo "[ OK ]" || echo "[ Failed ]"

    return 0
  }

  # stop
  function stop()
  {
    ! _status && echo "${SERVICE} is not running." && return 0

    echo "Stop ${SERVICE}."
    nohup ${BINDIR}/stopMysql.sh > /dev/null

    _wait "MYSQLD" "stop" && echo "[ OK ]" || echo "[ Failed ]"

    return 0
  }

  # restart
  function restart()
  {
    _status && stop
    start

    return 0
  }

  # status
  function status()
  {
    _status && echo "${SERVICE} is running..." || echo "${SERVICE} is stop."
    return 0
  }

  # status
  function _status()
  {
    ps cax | grep mysqld > /dev/null

    return $?
  }
}

#  php main
function PHP()
{
  SERVICE="php"

  # check php version
  function check()
  {
    cat ${HTTPD_CONF} | grep -e "php5_module\|php7_module" | awk '{print $3}' | sed -e "s#${PHPDIR}/##g" | sed -e "s#/.*##g" 
    return 0
  }

  # select php version
  function change()
  {
    local ans
    local php_ver=''
    local php_vers=($(ls ${PHPDIR} | grep php))

    while :;do
      echo ""
      echo "=="
      echo -n "Now PHP Version: ";check
      echo "=="
      echo ""
      echo "Please select PHP version number."
      local -i count=0
      for v in ${php_vers[*]};do
        echo " [${count}] ${v}"
        count=$count+1
      done
      echo " [${count}] exit"
      echo -n "> "
      read ans
      if [ ${ans} -le ${count} ];then
        if [ ${ans} -eq $count ];then
          return 0
        else
          php_ver=${php_vers[${ans}]}
        fi
        break
      fi
    done

    if _edit_httpd_conf "${php_ver}" && _edit_bash_profile "${php_ver}";then
      echo "Changed PHP version to ${php_ver}."
      echo "Httpd restart."
      HTTPD && restart
    fi
    return 0
  }

  # php.ini
  function conf()
  {
    local php_ver="$(check)"
    local php_conf="${PHPDIR}/${php_ver}/conf/php.ini"
    local php_conf_back="${php_conf}.back"

    echo "Now PHP Version: ${php_ver}"
    echo "To change the php.ini file ?"
    if ! _ynselecter;then
      return 0
    fi

    [ ! -f ${php_conf} ] && Err "Default 'php.ini' is not found."
    [ ! -f php_conf_back ] && cp ${php_conf} ${php_conf}.back

    while vi ${php_conf} || :;do
      echo "Edit the end ?"
      if _ynselecter;then
        echo "Httpd restart ?"
        if _ynselecter;then
          HTTPD && restart && break
        else
          break
        fi
      fi
    done

    return 0
  }

  # php debug
  function a()
  {
    local path="/tmp/"
    local name="$(date "+%Y%m%d%H%I%S").php"
    local file="${path}${name}"
    local opened="false"

    echo "<?php" > ${file}

    trap 'rm ${file}; exit 0' 1 2 3 15

    if [ ! -f ${file} ];then
      err "php file is not found."
    fi

    while vi ${file} || :;do
      echo ""
      php ${file}
      echo ""

      echo "Continue ?"
      if ! _ynselecter;then
        rm ${file}
        break
      fi
    done

    return 0
  }


  # edit httpd.conf
  function _edit_httpd_conf()
  {
    local before=$(cat ${HTTPD_CONF} | grep "${PHPDIR}" | grep -e "php.*/modules/libphp5.so\|php.*/modules/libphp7.so")
    local after=

    if echo ${1} | grep "php7";then
      after="LoadModule php7_module        ${PHPDIR}/${1}/modules/libphp7.so"
    else
      after="LoadModule php5_module        ${PHPDIR}/${1}/modules/libphp5.so"
    fi

    if sed -i "" -e "s#${before}#${after}#" ${HTTPD_CONF};then
      return 0
    else
      return 1
    fi
  }

  # To changed php version, Write to .bash_profile php path
  function _edit_bash_profile()
  {
    local bash_profile="${HOME}/.bash_profile"
    if [ ! -e ${bash_profile} ];then
      echo "${bash_profile} is not found."
      return 0
    fi

    local reg="export\\ PATH=${PHPDIR}/php.*/bin:\\\$PATH"
    if [ $(cat "${bash_profile}" | grep "${reg}" | wc -l) -eq 1 ];then
      local before=$(cat ${bash_profile} | grep "${reg}")
      local after="export PATH=${PHPDIR}/${1}/bin:\$PATH"
      if ! sed -i "" -e "s#${before}#${after}#" ${bash_profile};then
        return 1
      fi
    else
      echo "${after}" >> ${bash_profile}
      echo "Add 'MAMP PHP PATH' to .bash_profile."
    fi

    echo "Execute 'source ${bash_profile}'"
    return 0
  }

  return 0
}

#  Waiting to be processed
function _wait()
{
  local end=

  if [ "${2}" = 'start' ];then
    end=0
  elif [ "${2}" = 'stop' ];then
    end=1
  else
    return 1
  fi

  ${1}
  echo -n "Please wait..."
  while :;do
    _status
    [ $? -eq ${end} ] && return 0
    echo -n "."
  done
}

#  Yes or No Selecter
function _ynselecter()
{
  while true;do
    local ans
    echo "Please select. [y/N]"
    echo -n "> "
    read ans
    if [ -z ${ans} ];then
      ans="FALSE"
    fi
    case ${ans} in
      y)
        return 0
        ;;
      N)
        return 1
        ;;
      *)
        ;;
    esac
  done
}

#  Output error message and Processing end
function Err()
{
  echo "Error: ${1}";exit 1
}

[ ${#} -le 0 ] && HELP && exit 1
Main ${*}

exit 0
